[package]
name = "migo-hqm-server"
version = "1.0.5"
authors = ["John Eriksson <john.eriksson.16@gmail.com>"]
edition = "2018"

[dependencies]

nalgebra = "0.22"
tokio = { version = "1.0", features = ["net", "time", "macros", "rt-multi-thread", "sync"] }
rust-ini = "0.15" # INI For configuration
bytes = "1.0"
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
tracing-appender = "0.1"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3