[package]
name = "rust_hqm_server"
version = "0.1.0"
authors = ["John Eriksson <john.eriksson.16@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.21"
tokio = { version = "0.2", features = ["udp", "time", "macros", "rt-core"] }

[profile.dev]
opt-level = 2