[package]
name = "migo-hqm-server"
version = "1.8.0"
authors = ["John Eriksson <john.eriksson.16@gmail.com>"]
edition = "2018"

[dependencies]

nalgebra = "0.31"
tokio = { version = "1.21", features = ["net", "time", "macros", "rt-multi-thread", "sync", "fs"] }
rust-ini = "0.15" # INI For configuration
bytes = "1.2"
reqwest = { version = "0.11.12", default-features = false }
tracing = "0.1.26"
tracing-subscriber = "0.2.19"
tracing-appender = "0.1.2"
chrono = "0.4"
num-integer = "0.1.43"
uuid = { version = "0.8", features = ["v4"] }

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3