[package]
name = "migo-hqm-server"
version = "1.2.2"
authors = ["John Eriksson <john.eriksson.16@gmail.com>"]
edition = "2018"

[dependencies]

nalgebra = "0.26.1"
tokio = { version = "1.4", features = ["net", "time", "macros", "rt-multi-thread", "sync", "fs"] }
rust-ini = "0.15" # INI For configuration
bytes = "1.0"
reqwest = { version = "0.11", default-features = false }
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
tracing-appender = "0.1"
chrono = "0.4"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3