[package]
name = "rust_hqm_server"
version = "0.1.0"
authors = ["John Eriksson <john.eriksson.16@gmail.com>"]
edition = "2018"

[dependencies]

nalgebra = "0.22"
tokio = { version = "0.3.5", features = ["net", "time", "macros", "rt", "rt-multi-thread", "sync"] }
rust-ini = "0.15" # INI For configuration
bytes = "0.6.0"
tracing = "0.1.22"
tracing-subscriber = "0.2.15"
tracing-appender = "0.1"

[profile.dev]
opt-level = 2

[profile.release]
opt-level = 3