on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Migo HQM Server Build
env:
  BIN: migo-hqm-server

jobs:
  build:
    runs-on: ${{ matrix.platform.os }}
    strategy:
      fail-fast: false
      matrix:
        platform:
          - target: x86_64-pc-windows-msvc
            os: windows-latest
          - target: aarch64-pc-windows-msvc
            os: windows-latest
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
          - target: armv7-unknown-linux-gnueabihf
            os: ubuntu-latest
          - target: armv7-unknown-linux-musleabihf
            os: ubuntu-latest
          - target: arm-unknown-linux-gnueabihf
            os: ubuntu-latest
          - target: arm-unknown-linux-musleabihf
            os: ubuntu-latest
          - target: i686-unknown-linux-gnu
            os: ubuntu-latest
          - target: i686-unknown-linux-musl
            os: ubuntu-latest
          - target: i686-unknown-freebsd
            os: ubuntu-latest
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest
          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest
          - target: x86_64-unknown-freebsd
            os: ubuntu-latest
          - target: riscv64gc-unknown-linux-gnu
            os: ubuntu-latest
          - target: loongarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: loongarch64-unknown-linux-musl
            os: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Cache cargo & target directories
        uses: Swatinem/rust-cache@v2
      - name: Install musl-tools on Linux
        run: sudo apt-get update --yes && sudo apt-get install --yes musl-tools
        if: contains(matrix.platform.target, 'musl')
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: "build"
          target: ${{ matrix.platform.target }}
          toolchain: "stable"
          args: "--locked --release"
          strip: true
      - run: |
          7z a migo-hqm-server-${{ matrix.platform.target }}.zip config.ini README.md example_replay_integration.py ".\target\${{ matrix.platform.target }}\release\migo-hqm-server.exe"
        shell: bash
        if: matrix.platform.os == 'windows-latest'
      - run: |
          tar -czvf migo-hqm-server-${{ matrix.platform.target }}.tar.gz config.ini README.md example_replay_integration.py -C target/${{ matrix.platform.target }}/release migo-hqm-server
        shell: bash
        if: matrix.platform.os != 'windows-latest'
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: "migo-hqm-server-*"



